# -*- coding: utf-8 -*-
"""
Created on Sat Mar  7 20:28:40 2020

@author: ROG

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

fibonnaci = [1, 2]


number = 0
sum = 0
while((fibonnaci[-1] + fibonnaci[-2]) < 4000000):
    number = fibonnaci[-1] + fibonnaci[-2]
    fibonnaci.append(number)
    if(fibonnaci[-1]%2 == 0):
        sum = sum + fibonnaci[-1]

print(fibonnaci)
print(sum)